apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::663976361185:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::663976361185:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-V6T9YO6TSO4A
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: 2021-05-26T07:50:31Z
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: 2021-05-26T07:50:31Z
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1416"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a87a0e3a-aa35-43f2-b564-b43153c87c76
